name: AI Change (Issues -> PR)

on:
  issues:
    types: [opened, edited, reopened, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run-ai-change:
    if: contains(github.event.issue.labels.*.name, 'ai-change')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install openai

      - name: Run AI script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node .github/scripts/ai-change.mjs
